version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./backups:/app/backups
    environment:
      - MONGO_URI=mongodb://mongodb:27017/remotehustle
      - SECRET_KEY=your_secret_key
    depends_on:
      - mongodb
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M

  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./backups:/backups
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: {}
